### ISSUE TITLE
Witch changes grass block to dirt

### ISSUE THREAD

**Issue by WSDguy2014** [maikerumine/mobs_mc#100]
https://streamable.com/pdt19

**Comment by kingoscargames** [comment]
yeah i saw this too

**Comment by kingoscargames** [comment]
It doesn't only replace grass but also other blocks (witch replaces blocks with dirt #112)

**Comment by Wuzzy2** [comment]
This issue has been fixed in https://github.com/maikerumine/mobs_mc/commit/90194e80aa9b39a786caaf603f20454de521a77d.

It can be closed.
