### ISSUE TITLE
Mobs randomly teleport upwards … again!

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#102]
Yes, this old bug is back! Or was it never fixed? No idea!

From time to time, some mobs like zombies or witches just randomly teleport a short distance upwards while chasing you.

**Comment by kingoscargames** [comment]
I also saw silferfish do this.
EDIT:*silver

**Comment by kingoscargames** [comment]
The witch mobs also do this

**Comment by maikerumine** [comment]
I believe this is a pathfinding glitch.

**Comment by Wuzzy2** [comment]
I have posted this on Mobs Redo:
https://github.com/tenplus1/mobs_redo/issues/107

TenPlus1 claims it's fixed, but the fix doesn't work for me.

**Comment by Wuzzy2** [comment]
Fixed in Mobs Redo.
