### ISSUE TITLE
Melee aggresive mobs shouldn't be able to hit from too far

### ISSUE THREAD

**Issue by leorockway** [maikerumine/mobs_mc#107]
It seems like zombies / endermen (to put an example) can hit the player from farther than 1 node away. Since they do melee damage, that's not right. The player should be able to have a node in between him and the zombie / ender and not get hit. Also, endermen shouldn't be able to hit the player if the player is hidding under a block in front of the enderman (I can post screenshots to clarify if this doesn't make sense).

Mobs also shouldn't be able to hit through doors.

**Comment by kingoscargames** [comment]
"Mobs also shouldn't be able to hit through doors."  

from the wiki (http://minecraft.gamepedia.com/Zombie):
![image](https://user-images.githubusercontent.com/29333817/28107879-d4e17946-66e9-11e7-8a4a-109513adb24d.png)
"Zombies can deal damage through closed doors."

**Comment by leorockway** [comment]
That link also says "Zombies can _sometimes_ deal damage through a closed door". (Emphasis mine).

**Comment by Wuzzy2** [comment]
Please look at #120.

**Comment by Wuzzy2** [comment]
Please look at #123.

**Comment by Wuzzy2** [comment]
Is the distance OK now? I think it is.

**Comment by leorockway** [comment]
Much better after https://github.com/maikerumine/mobs_mc/pull/126

**Comment by leorockway** [comment]
I'll test on the Minecraft demo if zombies can attack through doors and report back.

**Comment by Wuzzy2** [comment]
Attack range is fixed according to leorockway. The other talk in this issue is off-topic, I'll open another one.
