### ISSUE TITLE
Death animation is randomly repeating for many mobs

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#11]
The death animation is randomly repeating for many mobs, for example, the skeleton.

**Comment by maikerumine** [comment]
I think this is in the mobs_redo code, as this has happened in earlier versions of this mod when I was using blockmens zombies.  sadly, i couldn't fix without changing the api, and that gets old when ten keeps changing the api.  Keeping dependancy to mobs_redo should come to an end I think, to better preserve the integrity of this mod.
I cannot tell you how many times I rewrote my mobs api to "merge" his updates and removal of code.  LOL

**Comment by Wuzzy2** [comment]
I am strongly opposed to combining mob API with mobs themselves. Those must be strictly kept separate IMO. The mob situation in the modding community is already terrible enough.
Why not just informing TenPlus1 about the Mobs Redo bugs instead, or even better: File a PR?

**Comment by 22i** [comment]
@maikerumine @Wuzzy2  mobs redo has been updated recently with animation flag for looping

https://github.com/tenplus1/mobs_redo/issues/67 write this in the animation table `die_loop = false` near die_start and die_end

**Comment by Wuzzy2** [comment]
@22i: Sorry, just adding `die_loop = false` doesn't do the trick. Tested with evoker and fresh Mobs Redo. I think the animation speed, start and stop frame need to be fixed as well, as explained by TenPlus1 in https://github.com/tenplus1/mobs_redo/issues/67.

You seem to be the perfect person to fix this, as you are most familiar with your own models.

**Comment by Wuzzy2** [comment]
It turns out it was a Mobs Redo bug.
When updating Mobs Redo now, all death animations are now finally working.
