### ISSUE TITLE
witch replaces blocks with dirt  (even BEDROCK and VOID BLOCKS in MineClone2!)

### ISSUE THREAD

**Issue by kingoscargames** [maikerumine/mobs_mc#112]
![screenshot_20170710_175054](https://user-images.githubusercontent.com/29333817/28027139-5f06e154-6598-11e7-8230-2fcf6f5ce16f.png)
![screenshot_20170710_175059](https://user-images.githubusercontent.com/29333817/28027138-5f0081ec-6598-11e7-9a89-a13012cb7946.png)

**Comment by kingoscargames** [comment]
this is probably the same as: https://github.com/maikerumine/mobs_mc/issues/100

**Comment by WSDguy2014** [comment]
Omg, is this used for breaking bedrock?

**Comment by kingoscargames** [comment]
maybe

**Comment by kingoscargames** [comment]
but there is no bedrock in mtg

**Comment by kingoscargames** [comment]
yep i tested it

**Comment by kingoscargames** [comment]
![screenshot_20170711_141303](https://user-images.githubusercontent.com/29333817/28067839-419828c0-6643-11e7-8b76-3d7ec26e56bc.png)
![screenshot_20170711_141306](https://user-images.githubusercontent.com/29333817/28067838-418ec226-6643-11e7-8b8c-7c570eabc12b.png)
![screenshot_20170711_141424](https://user-images.githubusercontent.com/29333817/28067855-4be9d206-6643-11e7-8ae6-7c105b4789c3.png)

**Comment by Wuzzy2** [comment]
Oh crap.
