### ISSUE TITLE
mc like textures for the wither and wither skeleton

### ISSUE THREAD

**Issue by kingoscargames** [maikerumine/mobs_mc#124]
<img width="32" alt="mobs_mc_wither" src="https://user-images.githubusercontent.com/29333817/28490895-82aeb96e-6ee5-11e7-917f-764c3b14e9c0.png">

![texture testing3](https://user-images.githubusercontent.com/29333817/28456853-13e486ee-6e04-11e7-84af-525997afa9ca.png)

(I only edited the textures already used, NOT the mc textures.)
EDIT:the wither skeleton texture is a edited version of the normal skeleton texture used right now
EDIT2: updated the wither texture( the pixels aren't shown in game). and removed the wither skeleton texture from this post

**Comment by Wuzzy2** [comment]
The wither texture is good.
The wither skeleton skull (actual head, block and wither particle) is pretty dark, it's hard to recognize the eyes. Just look at the mob head (block). Can you fix this, please?

I am in favor of all changes eliminating the weirdness of Pixel Perfection, so :+1: for the general idea.

**Comment by kingoscargames** [comment]
I could make the wither skeleton texture a little bit brighter?

**Comment by kingoscargames** [comment]
Also one question can i use a color from the mc texture? (not copy it)

**Comment by Wuzzy2** [comment]
Yes. Colors can't be owned. :D 
Just make it so the skull is easier to see as skull (esp. the eyes).

**Comment by kingoscargames** [comment]
![wither skeleton old - new](https://user-images.githubusercontent.com/29333817/28490859-908f8b36-6ee4-11e7-9bbe-146f48b80941.png)
new:
<img width="32" alt="mobs_mc_wither_skeleton" src="https://user-images.githubusercontent.com/29333817/28490862-a9d2b3e8-6ee4-11e7-8e8e-cebb633a8186.png"> 
<img width="4" alt="mobs_mc_temp_wither_projectile" src="https://user-images.githubusercontent.com/29333817/28490912-d83a6ec8-6ee5-11e7-88de-2c04987f2fff.png">
(I just turned up the brightness by 20)
(Also i updated the wither texture a little bit( 8 pixels) because some colors looked a little weird next to each other, so updated them to use the mc color and l turned them upside down to not have the exact same place as mc.)

**Comment by kingoscargames** [comment]
i also edited the spawn icons for them:
<img width="16" alt="mobs_mc_spawn_icon_wither" src="https://user-images.githubusercontent.com/29333817/28490941-788e8bca-6ee6-11e7-9b55-4b8513f7c557.png">
<img width="16" alt="mobs_mc_spawn_icon_witherskeleton" src="https://user-images.githubusercontent.com/29333817/28490942-7890f6ee-6ee6-11e7-9352-51d7d4d89141.png">

**Comment by Wuzzy2** [comment]
Wither textures and spawn icons added! Thank you.
