### ISSUE TITLE
Evoker's arms turn invisible when killed (error in the texture) 

### ISSUE THREAD

**Issue by kingoscargames** [maikerumine/mobs_mc#127]
![screenshot_20170724_134815](https://user-images.githubusercontent.com/29333817/28522968-9aef1172-707a-11e7-8aff-31a777e29ac9.png)

Some part are missing in the texture 
<img width="864" alt="evoker" src="https://user-images.githubusercontent.com/29333817/28522999-bcbfe0ec-707a-11e7-816a-9ad1939a9c9d.png">
i fixed it: 
<img width="32" alt="mobs_mc_evoker_base" src="https://user-images.githubusercontent.com/29333817/28523007-ca5fa7aa-707a-11e7-94ff-7bb9899c98e7.png">
![screenshot_20170724_141744](https://user-images.githubusercontent.com/29333817/28523035-e84d2f76-707a-11e7-91b6-74c8201e4039.png)

**Comment by Wuzzy2** [comment]
Fixed. Thanks!
