### ISSUE TITLE
check the pull request - updating mob looks and merge it

### ISSUE THREAD

**Issue by 22i** [maikerumine/mobs_mc#133]
@maikerumine @Wuzzy2 here it is https://github.com/maikerumine/mobs_mc/pull/132

**Comment by Wuzzy2** [comment]
Whoops. I must have forgotten this. I was so busy with MCL2.

It's OK to poke me again, but no need to open an issue for that, a new post with an “\@mention” in the PR would work, too.

**Comment by 22i** [comment]
is poking done with @Wuzzy2  right?

**Comment by Wuzzy2** [comment]
Yes.
