### ISSUE TITLE
rabbit no longer working with new updated mobs-api. luaentity-fail

### ISSUE THREAD

**Issue by silelmot** [maikerumine/mobs_mc#135]
Hi there.
i recognized the rabbit doesnt work anymor after mobs-api got updated.
it exists with a luaentity-fail. luaentity is nil

**Comment by Wuzzy2** [comment]
Oh man. Why does TenPlus1 keep **constantly** breaking the API without warning?!
\>_>

I haven't tested this so far, however.

**Comment by Wuzzy2** [comment]
Confirmed and fixed. Should now work with Mobs Redo 1.40.
Ouch, I didn't realize `mobs_mc` was completely **broken**. Sorry.
