### ISSUE TITLE
Texture sources?

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#20]
Such a question, where do you got the mob textures from?

**Comment by kingoscargames** [comment]
Some are from default mc

**Comment by Wuzzy2** [comment]
Okay, this clearly needs to be fixed. @maikerumine: Can you please list which ones?

By the way, do you know of any free/libre 16×16 MC texture packs? That would make fixing this very easy.

Or would it be possible to use the textures of the original model repository (I don't know where it is anymore).

**Comment by maikerumine** [comment]
I am at a loss, all the textures came from 22i except sheep.

**Comment by 22i** [comment]
most are from default minecraft

-free/libre 16x16 texture pack could be
pixel perfection https://www.planetminecraft.com/texture_pack/131pixel-perfection/
jolicraft http://www.jolicraft.com/

**Comment by leorockway** [comment]
Those two texture packs look great and using either would stop the dependency on nonfree Faithful for MineClone :D

**Comment by Wuzzy2** [comment]
Faithful is actually **not** “non-free” (scroll down to “Terms of use”), the main problem is that it is 32×32. https://minecraft.curseforge.com/projects/faithful-vanilla

Pixel Perfection is a good candidate, but maybe a bit too high contrast. But that's maybe okay.
Jolicraft looks interesting, but I can't find any evidence of a license. But the author seems to be liberal, so maybe someone could ask for this texture pack to be released explicity under public domain or a libre license (like CC BY 4.0 or CC BY-SA 4.0).

**Comment by 22i** [comment]
We could use Minecraft default textures but with a small color tint and textures rotated on their head or 90 degress?

**Comment by Wuzzy2** [comment]
No. That's still an obvious copyright violation.

Well, it looks currently we have 3 options for textures:

* Pixel Perfection (CC BY-SA 4.0)
* Jolicraft (custom “license”, see http://www.jolicraft.com/ FAQ no. 5)
* Find us an artist like @Doloment

What's your vote? I'm currently undecided.

**Comment by leorockway** [comment]
I like the way both Jolicraft and Pixel Perfection look, but I feel Jolicraft is less close to vanilla MC than Pixel Perfection. I don't know if that would be a con.

I like that Pixel Perfection has a clear license as opposed to Jolicraft's almost WTF License that's not really explicit.

While it would be nice to have our very own texture, that's a lot of work that takes time and in the meantime we'd still be using nonfree Faithful.

I think I would vote Pixel Perfection.

**Comment by Wuzzy2** [comment]
I vote for Pixel Perfection.

**Comment by 22i** [comment]
found some more libre texture packs
J0Pack https://www.planetminecraft.com/texture_pack/j0pack/
Mizuno's 16 Craft https://www.planetminecraft.com/texture_pack/mizunos-16-craft/
Fox-Craft https://www.planetminecraft.com/texture_pack/-fox-craft-/
Alvoria's Sanity https://www.planetminecraft.com/texture_pack/alvorias-sanity-pack/
CanterlotCraft https://www.planetminecraft.com/texture_pack/my-little-minecraft/
sandy-dreams https://www.planetminecraft.com/texture_pack/sandy-dreams/
CrafteePack https://www.planetminecraft.com/texture_pack/crafteepack/ no license statted

**Comment by Wuzzy2** [comment]
Only J0Pack is actually free/libre (CC BY). But it is very old, for MC 1.7.10.
The rest is either NC or has no license (=full copyright), so non-free. **“Creative Commons” is *not* a synonym for “free license”.**

To clarify, of all CC licenses, only these 3 licenses are considered free:

* CC0
* CC BY
* CC BY-SA

**Comment by 22i** [comment]
i vote for pixel perfection

**Comment by maikerumine** [comment]
Pixel Perfection looks the best

**Comment by Wuzzy2** [comment]
The question is answered and we have now Pixel Perfection textures. Closing.
