### ISSUE TITLE
Reorganize mob items

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#24]
I suggest we move all item definitions into a central file `items.lua`.

Also, we add a file `gameconfig.lua` in which  variables for item names are defined which the individual mobs then use instead of the actual name.
For example, in `rabbit.lua`, it should no longer say explicitly say `"mobs_mc:rabbit_hide"` for one of its drops, but something like `mobs_mc.items.rabbit_hide`. This is a variable which contains the actual itemstring.

By doing this, subgame integration is made WAY easier, now subgame authors only have to touch `gameconfig.lua` and can leave all other files alone. This is especially important if subgames choose to provide their own items (like MCL2 does).

I'm planning to work on this sooner or later. But I like to hear your opinion on this.

**Comment by maikerumine** [comment]
YES!!  I completely agree, and will make this happen tomorrow.  Currently it is to specific between mc2 and general mobs_mc, compatibility is difficult.

**Comment by Wuzzy2** [comment]
OK, if you insist on doing this, I will continue on working on the mobs instead. But please fix #26 first.

**Comment by Wuzzy2** [comment]
I'm still not happy with the items situation, so I decided to work on this right now.

**Comment by maikerumine** [comment]
How to make common drops that source from two different places?

**Comment by Wuzzy2** [comment]
Idea:
Add a file `gameconfig.lua` which contains a bunch of “fake constants” for all item names used in this mod. Like this:

```
mobs_mc.itemstrings.feather = "mobs_mc:feather"
mobs_mc.itemstrings.porkchop_raw = "mobs_mc:porkchop_raw"
mobs_mc.itemstrings.dirt = "default:dirt"
```

And so on. For items from other mods, we try to prefer Minetest Game. If Minetest Game doesn't offer this item, use a builtin definition.
And in, let's say, `chicken.lua`, one could write `drops = --[[ … ]] mobs_mc.itemstrings.feather`.

Now this doesn't solve the problem of subgame integration yet. So I have this idea: Depend on an optional mod which we don't actually ship (think of it as an “abstract mod” or “interface”), let's say “mobs_mc_item_defs`.
This mod will, if found, define.

This has the following implictions:
* If used as standalone mod in Minetest Game, it uses all builtin items and just works out of the box. No additional mod required
* If needs to be integrated in any subgame, the following needs to be done:
    * Add `mobs_mc`
    * Add `mobs_mc_gameconfig` and set all the correct item names. For MCL2, this could be used to switch `default:dirt` to `mcl_core:dirt` and also point to all of the subgame-defined mob items from `mcl_mobitems`.


Benefit: `mobs_mc` is kept completely intact even after integration.
Downside: If subgame adds its own mob items (like MCL2), `mobs_mc` contains ca. 600 lines of unused code.

The downside could be fixed by moving all items into another mod, but this may be over-engineered.

What do you think of this? Does this sound feasible to you?

**Comment by Wuzzy2** [comment]
No comments? :-(

Not fully fixed IMO, see previous comment.

**Comment by maikerumine** [comment]
I am sorry!  I only merged this, it automaticly closed.  :/  I haven't been commenting as been swamped with many things.
I fully trust your code and openly accept your input and skill, hense the fast merges and updates to my live server with those changes.  I probably should look more into the changes, but it all works fine on my end, no major issues.

As for the comment at hand, I like the idea of having a standard items drop, that can be shared through different subgames.  I am thinking if you were to dedicate all your specific drops and items from mods like nether, end, etc, to mobs_mc - then it would be easier and cleaner in the longrun, as these items wouldn't need specific dependancies regardless of origin.

**Comment by Wuzzy2** [comment]
Working on this now.
