### ISSUE TITLE
Commit 3c1d5d043a04bc9682242678df706878600f362e went seriously wrong

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#26]
3c1d5d043a04bc9682242678df706878600f362e seems to have gone seriously wrong. Please revert this.

This commit seems to have reverted *all* of the changes I did in previous commits. :-(

Specifically:
- Chicken
- Silverfish
- Polar bear
- Creeper
- Slime
- Magma cube
- Sheep
- Squid
- Files

**Comment by Wuzzy2** [comment]
Ummm … what?! Why did you close this without reason?
This is not fixed. The bad commit has not been reverted. :-(

**Comment by maikerumine** [comment]
No no no :(  I hate git.  I don't understand it.

**Comment by maikerumine** [comment]
I thought I merged by copying your git code and putting in mine.

**Comment by maikerumine** [comment]
How do i revert?  it seems there is too many requests that overlap and conflict, this is getting tiresome.

**Comment by maikerumine** [comment]
Your changes are intact.  What i did was copy all your changes and overwrote my repo, so your changes still took in order to fix the conflicts.  Please see the bat, it still has your latest changes.

**Comment by maikerumine** [comment]
I tried to revert, it won't let me.  what do i do?

**Comment by Wuzzy2** [comment]
OK, this looks fixed now, all my old changes are back in. Although it has nothing to do with the referenced issue. Whatever.

>  What i did was copy all your changes and overwrote my repo, so your changes still took in order to fix the conflicts.

Okay, this is not something which should be done, usually. That's what Git is for. It still may be valid solution (although lazy), but it is very important to check the diff (`git diff`) before committing, just to make sure you don't commit crap.

I strongly recommend you read through the Git tutorial at least up to chapter 7 (if you haven't already), hopefully things will be less confusing/frustrating for you. If you're still learning, you could try practicing on a test repository

Merging and reverting are everyday actions in Git, you should be able to do those two things in your sleep.
