### ISSUE TITLE
Enderman eyes

### ISSUE THREAD

**Issue by kingoscargames** [maikerumine/mobs_mc#29]
I believe endermen have a 2nd texture that is for the eyes and that gets overlayed on the base texture

**Comment by kingoscargames** [comment]
This:
![2017-06-21-00-01-06-608450907](https://user-images.githubusercontent.com/29333817/27357979-c7c9294c-5614-11e7-8204-e4b8710d9542.png)

**Comment by 22i** [comment]
this would be an easy fix - do enderman always have pink eyes?

textures = {{"enderman.png^enderman_eyes.png"}},

**Comment by kingoscargames** [comment]
yes

**Comment by kingoscargames** [comment]
i believe they made it that way is because whet its invisible the translucent eyes are still there.
edit: *when
