### ISSUE TITLE
spider eyes (not the item)

### ISSUE THREAD

**Issue by kingoscargames** [maikerumine/mobs_mc#39]
![spider_eyes](https://user-images.githubusercontent.com/29333817/27534064-fd6dd6b0-5a65-11e7-8bad-789269542335.png)
I don't know how this texture is used, probably when its invisible.

**Comment by leorockway** [comment]
I'm not sure what you're asking here, but the eyes of the spider should glow at night and not glow during the day.

**Comment by Wuzzy2** [comment]
This is probably a simple texture overlay, like for endermen.

Note we can not use copyrighted textures.

**Comment by kingoscargames** [comment]
![spider_eyes](https://user-images.githubusercontent.com/29333817/27577378-c0bee5e0-5b20-11e7-94b4-cb6d6fceb71a.png) 32x32 texture
