### ISSUE TITLE
"default_steelblock"

### ISSUE THREAD

**Issue by kingoscargames** [maikerumine/mobs_mc#40]
![screenshot_20170626_125347](https://user-images.githubusercontent.com/29333817/27536215-80fcf2f6-5a6e-11e7-95cb-41d568005a27.png)

should be changed to default_steel_block

**Comment by Wuzzy2** [comment]
The texture bug is real, your suggested bugfix is not. Iron golems should not have any blood texture.

By the way: What happened to your minimap? It looks broken.

**Comment by kingoscargames** [comment]
a client mod that enables it but it becomes invisible,white or red. probably a bug (i dont know anything about csm).

**Comment by kingoscargames** [comment]
this hasnt got anything to do with this but:
![screenshot_20170627_103505](https://user-images.githubusercontent.com/29333817/27578457-6e09758c-5b24-11e7-983e-4a7f56882415.png)
