### ISSUE TITLE
Remove and replace non-free data

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#46]
Currently, `mobs_mc` is quite badly polluted with non-free data or data with dubious or unknown legal status.

IMO we should get rid of then as soon we can.

- [x] Remove non-free sounds
- [x] Remove non-free textures
- [x] Decide on a free texture pack to use
    - [x] Then replace all textures at once (requires #8)
- [x] Document licensing status of **all** files
   - [x] Sounds
   - [x] Models
   - [x] Textures
   - [X] Source code
- [x] Fix #86

**Comment by Wuzzy2** [comment]
@maikerumine: Can you please look into documenting the current licensing situation in a text file? Or at least partially (as good as you can)? Or at least clean up the messy license files we have now? That already will help a lot.

**Comment by maikerumine** [comment]
Sure thing.  :)

**Comment by Wuzzy2** [comment]
OK.
The only thing which has unclear licensing now are mob head textures; they are probably either based off Faithful textures or even original textures (not sure). The rest is free/libre and documented.

Mob heads will be revised very soon, I think.

**Comment by Wuzzy2** [comment]
All non-free stuff has been removed.
Licensing information is clearly stated in `LICENSE-media.md`.

`mobs_mc` is now perfectly safe to use.
