### ISSUE TITLE
Useless files api-mcorg.lua and api-mm-mcmods.lua?

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#54]
Is there any reason why the files `api-mcorg.lua` and `api-mm-mcmods.lua` exist?
Those files are not used in the code (no `dofile`).

Maybe let's just delete them, OK? Or do you keep these files for a reason?

**Comment by maikerumine** [comment]
Yes, as backups incase it decides to be mobs redo independent.  I'll probably delete as all old codes are not needed.

**Comment by Wuzzy2** [comment]
https://github.com/maikerumine/mobs_mc/commit/6159cd2c609ab1483cbf3e691bcb4ecf0eb6e38b
https://github.com/maikerumine/mobs_mc/commit/0c2d9326dcade3bb9e0db5573920f7c59cfc13d2
