### ISSUE TITLE
Sound licensing cleanup

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#6]
The licening of sounds is dubious, I suspect that a large chunk of the currents sounds fall under copyright.
Either the dubious sounds should be removed, replaced or we are lucky and some sounds turn out to be libre after all.

**Comment by maikerumine** [comment]
I agree completely.  I will be looking more into this and possibly making sounds myself if needed, the zombie, villager, pig. etc all sound suspicious.

**Comment by Wuzzy2** [comment]
In MineClone 2, I use free/libre sounds for cow and sheep.

**Comment by maikerumine** [comment]
I started this task, more todo later

**Comment by Wuzzy2** [comment]
I think all the sounds currently in `mobs_mc` are okay now as they come from somewhere within the MT community.
