### ISSUE TITLE
maikerumine is inept at fucking github

### ISSUE THREAD

**Issue by maikerumine** [maikerumine/mobs_mc#74]
how can i give you more powers to fix all my fucked up merges that were not in correct order?

**Comment by Wuzzy2** [comment]
Actually, the order in which you merge does not neccessarily matter that much. It depends on the situation.
What is more important is that you know what you merge and if there are conflicts, how to resolve them.

I am currently looking through the GitHub help to find an answer.
In the meantime, read this:
https://services.github.com/on-demand/intro-to-github/

**Comment by Wuzzy2** [comment]
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

**Comment by Wuzzy2** [comment]
You may also be interested in this:
https://help.github.com/articles/addressing-merge-conflicts/

Being able to resolve conflicts is very important for mastering Git.

**Comment by leorockway** [comment]
This is also a pretty good resource:
https://www.codecademy.com/learn/learn-git

**Comment by Wuzzy2** [comment]
@maikerumine: Do you still want to give me direct commit access to this repo (like you suggested initially)? I think all this PR nonsense is getting tiresome. ;-)

Have you read this?:
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/
This should answer the original quetion.

**Comment by Wuzzy2** [comment]
I am now officially a collaborator, so this can be closed.
