### ISSUE TITLE
What to do about mob heads?

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#78]
I am not sure what we should do with the mob heads. I am not happy the way they are done now.

I am inclined to say “remove” and just put aliases into `0_gameconfig.lua` and keep the mob drops.

Instead, we let the subgame add the heads. I think we already have way too many items in this mod and heads are not trivial. Heads are supposed to be rare anyway.

Well, at least that's my idea. But I am not sure. What do you think we should do with the mob heads?

Note for this mod, we only need 4 heads: zombie head, skeleton skull, wither skeleton skull and creeper head because those are the only ones which can be dropped from mobs.

See also: http://minecraft.gamepedia.com/Head

**Comment by Wuzzy2** [comment]
@kingoscargames

**Comment by maikerumine** [comment]
agreed, however they do drop under rare situation.. head textures were made by me based off existing back when this started.

**Comment by maikerumine** [comment]
we need for crafting wither in world.

**Comment by Wuzzy2** [comment]
Good point. It's just that I'm really not happy with adding another non-trivial component to the mod which is not a mob.
I feel that heads are something which make a lot of sense in a different mod. The current approach of `mobs_mc` is really “everything and the kitchen sink”. :D

At least heads are not as bad as with bow and arrows, which I think should really get outsourced (if we can).

I'm starting to think more and more that we might turn `mobs_mc` into a modpack with the core mod only for the raw mobs, and the other mods include the items. What do you think about this?



For a quick-and-dirty solution I think we just stick with the head items (for now) and just clean up the mess a bit. Also, I noticed my `mcl_heads` mod in MineClone 2 is just 47 lines long.

**Comment by kingoscargames** [comment]
Also would it be possible to use a model that uses the same textures as the mobs?
So that it would need less textures.
(i think that is how mc does it)

**Comment by Wuzzy2** [comment]
Now I think it is actually not that bad in having the mob heads in the mod. Mob head code has been simplified, they use the original mob textures, the code is actually rather short and the mob heads can be replaced if needed.
I think it's not a real problem anymore.
