### ISSUE TITLE
Rename files to follow conventions

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#8]
Current texture/sound/model file names are extremely chaotic and are a great invite for naming collisions.

Eventually, to keep things clean, all file names should follow naming conventions. Naming conventions dictate a file name like `<modname>_<actual_name>`, e.g. `mobs_mc_bat.png` instead of `bat.png`.

I think we should not worry about compability at all, since this mod is still very young and the file names are a serious mess.

This can be done safely for all model and mob texture files. For some textures, it might make sense to preserve the original name, like items or sounds **if** the file comes from a different semi-established mod. Simply to make the life of texture pack makers easier.
All `mcl_mobitems_` textures can keep their name.

Your opinion on this?

**Comment by maikerumine** [comment]
I accept this, it is way too confusing with the current mashup of media in this mod.

**Comment by Wuzzy2** [comment]
Okay, outlining concrete naming conventions:

* All craftitems get the same name as in the `mcl_mobitems` mod
* Spawn eggs:
   * `mods_mc_spawn_icon_<mob>.png`: For the Mobs-Redo-style spawn icon (depicting the mob)
   * `mods_mc_spawn_egg_<mob>.png`: For the spawn egg icon, must look like an egg (if we ever include those egg icons in the first place)
* Everything else: `mobs_mc_<whatever>`
   * Preferably with `<whatever>` based on the MC texture name, but not really important

**Comment by maikerumine** [comment]
Done.  After this weekend I will fix .

Sent from my MetroPCS 4G LTE Android device

----- Reply message -----

**Comment by Wuzzy2** [comment]
Today I'll work on cleaning up texture names.
