### ISSUE TITLE
Unchanged original mob textures

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#86]
Sadly, Pixel Perfection is incomplete and has no custom textures (= original MC textures) for the following mobs:

* [x] Llama (including carpets)
* [x] Vindicator
* [x] Evoker
* [x] Illusioner
* [x] Vex
* [x] Parrot
* [x] Skeleton Horse

I don't think the author of Pixel Perfection is going to update the texture pack anytime soon, so someone has to draw textures for these.

See also: #46.

**Comment by kingoscargames** [comment]
i made these textures:
<img width="32" alt="mobs_mc_vex" src="https://user-images.githubusercontent.com/29333817/28473442-d814c674-6e44-11e7-872c-473fb13b1291.png">
<img width="32" alt="mobs_mc_vex_charging" src="https://user-images.githubusercontent.com/29333817/28473443-d817a498-6e44-11e7-98b3-4e2bf5338ad3.png">
(i did NOT edit the default mc textures)

EDIT:A part of the textures is a recolored part of the default character.png (the hands).

**Comment by kingoscargames** [comment]
And these:
<img width="32" alt="mobs_mc_evoker_base" src="https://user-images.githubusercontent.com/29333817/28490176-98066940-6ed3-11e7-8990-82b1b7c6a3e9.png">
<img width="32" alt="mobs_mc_illusionist" src="https://user-images.githubusercontent.com/29333817/28490177-9806b292-6ed3-11e7-9ad2-a33bac06af30.png">
<img width="32" alt="mobs_mc_vindicator_base" src="https://user-images.githubusercontent.com/29333817/28490178-9806c80e-6ed3-11e7-9712-f30c018acba4.png">
(The textures are still "w.i.p.")
I did NOT edit the mc textures, i edited the "mobs_mc_villager_farmer.png`" from: https://github.com/maikerumine/mobs_mc/pull/122/files
EDIT:ignore this

**Comment by kingoscargames** [comment]
![mobs_mc_llama_gray](https://user-images.githubusercontent.com/29333817/28492873-45c62d18-6f0b-11e7-9b80-a8a73bceafc5.png)
<img width="64" alt="mobs_mc_llama_creamy" src="https://user-images.githubusercontent.com/29333817/28492871-45c57616-6f0b-11e7-8402-b6b38b9b55cb.png">
<img width="64" alt="mobs_mc_llama" src="https://user-images.githubusercontent.com/29333817/28492874-45c641d6-6f0b-11e7-879c-278beaf9c15d.png">
<img width="64" alt="mobs_mc_llama_brown" src="https://user-images.githubusercontent.com/29333817/28492875-45cc405e-6f0b-11e7-8999-03e403a7f6f2.png">
<img width="64" alt="mobs_mc_llama_white" src="https://user-images.githubusercontent.com/29333817/28492876-45ccb7fa-6f0b-11e7-93f8-4b368dedf30d.png">
<img width="64" alt="mobs_mc_llama_chest" src="https://user-images.githubusercontent.com/29333817/28492872-45c5f8d4-6f0b-11e7-9d3e-016a1dd53cff.png">
(I used some colors from mc but didnt copy anything and the chest is a edited version of "mobs_mc_horse_chest.png"(moved the texture))

**Comment by Wuzzy2** [comment]
Great! Now if the llama textures get included, the only thing which is missing for 100% free/libre textures are the llama carpets (`mobs_mc_decor_*`).

**Comment by Wuzzy2** [comment]
Old carpet textures have been removed. We're in the clear now!
