### ISSUE TITLE
Baby zombie / baby husk is too small

### ISSUE THREAD

**Issue by Wuzzy2** [maikerumine/mobs_mc#94]
The baby zombie/husk is way too small. It is really tiny, you will almost overlook it.

Just test this with `/spawnentity mobs_mc:baby_zombie` and see for yourself.

**Comment by kingoscargames** [comment]
it looks like this: ![screenshot_20170706_085804](https://user-images.githubusercontent.com/29333817/27899127-3e995054-6229-11e7-9bd5-baab914f7c29.png)
it should look something like this: 
![image](https://user-images.githubusercontent.com/29333817/27899152-559f9ef2-6229-11e7-9a75-99c7fae5789d.png)
(EDIT: the zombie in the first picture was jumping so it looked a little bit taller)
